document.write( '		<div class=\"column sidebar\">\n' );
document.write( '			<div class=\"header\">\n' );
document.write( '				<a href=\"./index.html\"><img src=\"./assets/img/global/pfp.png\" alt=\"Home\"></a>\n' );
document.write( '				<h1>Sterophonick\'s Own Little World</h1>\n' );
document.write( '				<p>wait i have a website now?</p>\n' );
document.write( '			</div>\n' );
document.write( '			<div class=\"navigation\">\n' );
document.write( '				<a href=\"projects.html\">Projects and Stuff</a><br />\n' );
document.write( '				<a href=\"dumps.html\">Dumps</a><br />\n' );
document.write( '				<a href=\"blog.html\">Blog</a><br />\n' );
document.write( '				<a href=\"gallery.html\">Gallery</a><br />\n' );
document.write( '				<a href=\"greetz.html\">Greetz</a><br />\n' );
document.write( '				<a href=\"links.html\">Links</a><br />\n' );
document.write( '			</div>\n' );
document.write( '			<div class=\"sidebar-bottom\">\n' );
document.write( '				<a href=\"https://github.com/Sterophonick" title="GitHub"><img src=\"./assets/img/global/github.png\" style=\"width:42px;height:42px;\"></a>\n' );
document.write( '				<a href=\"https://gbatemp.net/members/sterophonick.457315/" title="GBAtemp"><img src=\"./assets/img/global/tempy.webp\" style=\"width:42px;height:42px;\"></a>\n' );
document.write( '				<a href=\"https://youtube.com/sterophonick" title="YouTube"><img src=\"./assets/img/global/youtube.webp\" style=\"width:42px;height:42px;\"></a>\n' );
document.write( '				<a href=\"https://twitter.com/sterophonick" title="Twitter"><img src=\"./assets/img/global/twitter.png\" style=\"width:42px;height:42px;\"></a>\n' );
document.write( '			</div>' );
document.write( '		</div>\n' );
document.write( '		<div class=\"column sidebar-border\">\n' );
document.write( '			<!--bruh-->\n' );
document.write( '		</div>' );