document.write( '		<div class=\"column sidebar\">\n' );
document.write( '			<div class=\"header\">\n' );
document.write( '				<a href=\"./index.html\"><img src=\"./assets/img/global/pfp.png\" title=\"Atapi PFP by @ScottAllRubin!\"></a>\n' );
document.write( '				<h1>Sterophonick\'s Own Little World</h1>\n' );
document.write( '				<p>wait i have a website now?</p>\n' );
document.write( '			</div>\n' );
document.write( '			<div class=\"navigation\">\n' );
document.write( '				<a href=\"projects.html\"><img src=\"./assets/img/global/folder.png\"> Projects and Stuff</a><br />\n' );
document.write( '				<a href=\"misc.html\"><img src=\"./assets/img/global/misc.png\"> Miscellaneous Stuff</a><br />\n' );
document.write( '				<a href=\"dumps.html\"><img src=\"./assets/img/global/chip.png\"> Dumps</a><br />\n' );
document.write( '				<a href=\"blog.html\"><img src=\"./assets/img/global/notepad.png\"> Blog</a><br />\n' );
document.write( '				<a href=\"gallery.html\"><img src=\"./assets/img/global/gallery.png\"> Gallery</a><br />\n' );
document.write( '				<a href=\"greetz.html\"><img src=\"./assets/img/global/greetz.png\"> Greetz</a><br />\n' );
document.write( '				<a href=\"links.html\"><img src=\"./assets/img/global/links.png\"> Links</a><br />\n' );
document.write( '			</div>\n' );
document.write( '			<div class=\"sidebar-bottom\">\n' );
document.write( '				<a href=\"https://github.com/Sterophonick" title="GitHub"><img src=\"./assets/img/global/github.png\" style=\"width:42px;height:42px;\"></a>\n' );
document.write( '				<a href=\"https://gbatemp.net/members/sterophonick.457315/" title="GBAtemp"><img src=\"./assets/img/global/tempy.webp\" style=\"width:42px;height:42px;\"></a>\n' );
document.write( '				<a href=\"https://youtube.com/sterophonick" title="YouTube"><img src=\"./assets/img/global/youtube.webp\" style=\"width:42px;height:42px;\"></a>\n' );
document.write( '				<a href=\"https://twitter.com/sterophonick" title="Twitter"><img src=\"./assets/img/global/twitter.png\" style=\"width:42px;height:42px;\"></a><br/>\n' );
document.write( '				<a href=\"https://github.com/Sterophonick/sterophonick.github.io" style=\"font-size:14pt\">Website Source</a>\n ');
document.write( '			</div>' );
document.write( '		</div>\n' );
document.write( '		<div class=\"column sidebar-border\">\n' );
document.write( '			<!--bruh-->\n' );
document.write( '		</div>' );